name: Deploy React App to S3
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build React app
        run: yarn build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Debug AWS CLI configuration
        run: aws sts get-caller-identity
      - name: Deploy to S3
        run: |
          aws s3 sync ./dist/ s3://serveaseapp.com/ --delete
      #          aws s3 sync ./dist/ s3://servease-website.com/ --delete
      # Optional: Invalidate CloudFront cache if you're using CloudFront
#      - name: Invalidate CloudFront cache
#        run: |
#          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"